AllCops:
  NewCops: enable
  TargetRubyVersion: 3.2
  SuggestExtensions: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/SymbolArray:
  EnforcedStyle: brackets

Style/WordArray:
  EnforcedStyle: brackets

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 50

Metrics/ModuleLength:
  Max: 120

Metrics/ClassLength:
  Max: 120

Metrics/BlockLength:
  Max: 30

Metrics/CyclomaticComplexity:
  Max: 20

Metrics/AbcSize:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Layout/LineLength:
  Max: 140

Layout/LeadingCommentSpace:
  AllowRBSInlineAnnotation: true

# TODO: See: https://github.com/rubocop/rubocop/issues/14695
Layout/EmptyLineAfterMagicComment:
  Enabled: false
